### ISSUE TITLE
MacOS minimum version?

### ISSUE THREAD

**Issue by davidamis** [michaelrsweet/lprint#102]
The LPrint home page lists the minimum MacOS version as 10.8, but the installer requires 10.14. Is it possible to install LPrint on earlier systems?

**Comment by davidamis** [comment]
I missed that this was a closed issue.

**Comment by michaelrsweet** [comment]
You can install from source, but the binaries require a newer version (and LPrint 1.3 will be built for macOS 11 and higher)
