### ISSUE TITLE
Darkness stuck at 0 when printing from Linux

### ISSUE THREAD

**Issue by nickrbogdanov** [michaelrsweet/lprint#104]
On my print server I am using lprint with a Zebra 2844 in EPL2 mode.  On my client I am running Ubuntu 22.04 with CUPS, and trying to print a 4x6 label from evince.  The server is running the master branch of lprint and pappl, compiled from source.

I observed that the printed labels were very light, so I added a debug print in `lprint_epl2_rstartpage()` which told me that `options->print_darkness` is 0.  This causes a `D0` command to be sent to the printer.  I was not able to figure how how to override this darkness setting through the UI.

I do not see a darkness option anywhere in the Linux print dialog.  I see a "quality" option which doesn't seem to do anything (Draft/Normal/High).  I do see a `printer-darkness-configured` option in `.lprint.conf` which does not seem to have any effect on this setting.  I tried fixing it at 100, to no avail.

My current workaround is to modify the `lprint_epl2_rstartpage()` code to always send `D15` but this isn't a great solution.  I would prefer to have a way to set this to a fixed value server-side that is appropriate for the media/hardware in use (e.g. an old printer with a "weak" print head), so that every client doesn't have to manually adjust this parameter.

**Comment by michaelrsweet** [comment]
Hmm, the defaults (set either from the command-line or web interface) should be applied since it is unlikely the CUPS client is specifying the print-darkness attribute... Can you attach a copy of your .lprint.conf file? (you'll probably have to rename it with a .txt extension...)

**Comment by michaelrsweet** [comment]
I think I found the problem:

[master 65fa807] Use composite darkness value (Issue #104)
