### ISSUE TITLE
Dymo labelwriter duo 450 still having issues printing to tape

### ISSUE THREAD

**Issue by eriksl** [michaelrsweet/lprint#105]
Hi,

So very sorry for not coming back sooner.

I am now testing with the master branch, self-compiled. The tape printer now does produce something, but it's weird. I have made a png that consists of two black rectangles, a few pixels wide, the outer one to the edges of the image, the inner one a few pixels inside (so you get a black border, then a white rectangle, then a black rectangle, then white, from outside to inside).

The image I made is a png of 1000x120 pixels. When I print it, it only prints the top half of the im
age, on the bottom half of the tape... When I resize the image to 500x60 (just to see what happens), exactly the same happens. So this is kind of useless for me.

Maybe it has to do with that I cannot select a proper media type for the tape printer? It only allows for "label" type media.

This is the image I am trying to print:

![test](https://github.com/michaelrsweet/lprint/assets/1038982/6ceb9a3d-15c8-4a80-b064-89cc6df95f08)

This is what comes out:

![20230819_130037](https://github.com/michaelrsweet/lprint/assets/1038982/5025cc1f-1253-4ff6-a525-eef87f0c41e0)

_Originally posted by @eriksl in https://github.com/michaelrsweet/lprint/issues/62#issuecomment-1684919314_

**Comment by michaelrsweet** [comment]
Not able to look at this right now but will get back to you in a few weeks.

**Comment by eriksl** [comment]
Ok!

**Comment by michaelrsweet** [comment]
I think this is resolved in master (what will hopefully soon be 1.3.0...)
