### ISSUE TITLE
New Printer Request

### ISSUE THREAD

**Issue by nekoprog** [michaelrsweet/lprint#108]
Hello, I want to request for 4Barcode 4B-2054F support. The driver can be downloaded from here [https://www.seagullscientific.com/downloads/printer-drivers/4barcode-4b-2054f/](https://www.seagullscientific.com/downloads/printer-drivers/4barcode-4b-2054f/)

Let me know if it is possible.

**Comment by michaelrsweet** [comment]
The link you provided is to a Windows driver which doesn't help.

I also tried finding the manufacturer's web page for the printer without success...

Unless you can find real documentation on this printer or the formats that it supports, I can't really help you... Sorry...
