### ISSUE TITLE
Resizing and cropping 8.5x11 PDF

### ISSUE THREAD

**Issue by milkman0007** [michaelrsweet/lprint#111]
Here is the problem I am trying to solve. I have customers that want to print shipping labels from their label printer from sites that do not support thermal printing formats. The best example is like an eBay return label. It is formatted to be printed out of a desktop 8.5x11 printer and I want to crop, rotate, and resize, save as a PNG, and print it off from a 4x6 label printer. I am looking to do this printer side if possible. So I want the Windows print driver to send the PDF to the printer and then have the printer process the editing task. The PDF files are all very small, under 1MB.

What is the best approach: use PAPPL or even LPrint with MuPDF or something similar to edit the PDF? The reason I was thinking LPrint with PAPPL was in case I wanted to do some modifications to ZPL like if the data is coming in as a 4x6 label I want to reformat it to 3x7  or maybe get rid of the Win driver later on and go IPP.

**Comment by michaelrsweet** [comment]
Sorry, I have no plans of adding a feature like this to LPrint. If you want a printer that *does*, try the [Rollo Wireless Printer](https://www.rollo.com).

Proper implementation requires examination of the incoming PDF to determine what content is present, and to crop/scale that content onto the label(s).
