### ISSUE TITLE
Support for epson printers?

### ISSUE THREAD

**Issue by mykrowyre** [michaelrsweet/lprint#118]
Is there any possibility of supporting generic Epson 9 and 24 pin dot matrix printers in the future?

**Comment by michaelrsweet** [comment]
Well, LPrint is intended to be used with label and receipt printers, not dot matrix printers. [OpenPrinting](https://github.com/OpenPrinting/) has several printer applications that bundle the CUPS and Ghostscript dot matrix drivers already, and given the limited capabilities of those old printers I doubt there would be any advantage to developing a new "native" driver in PAPPL/LPrint.

**Comment by mykrowyre** [comment]
Thanks, only asked because the cups drivers for Epson are just so awful when printing graphics (such as pdf labels in this case).  If anyone could fix it I'm certain you could.  Sent from my iPhoneOn Jan 31, 2024, at 11:46 AM, Michael R Sweet ***@***.***> wrote:﻿
Well, LPrint is intended to be used with label and receipt printers, not dot matrix printers. OpenPrinting has several printer applications that bundle the CUPS and Ghostscript dot matrix drivers already, and given the limited capabilities of those old printers I doubt there would be any advantage to developing a new "native" driver in PAPPL/LPrint.
