### ISSUE TITLE
lprint server: Unable to create IPv6 listener for localhost:8631: Address family not supported by protocol

### ISSUE THREAD

**Issue by dreamcat4** [michaelrsweet/lprint#12]
Again there could be multiple different reasons for this one. Perhaps it's something to do with the server name, or the way the url address:port number string is being constructed. Or perhaps it's something like my system's unix permissions not letting your program open up a port. Not sure.

```sh
79° [id:~/.dev/lprint] master(+40/-0)* 1 ± sudo lprint server -o server-name=localhost -o server-port=8631
subcommand='server'
num_options=2
options[0].name='server-name', value='localhost'
options[1].name='server-port', value='8631'
num_files=0
F [2020-01-22T15:11:37Z] Unable to create IPv6 listener for localhost:8631: Address family not supported by protocol

θ79° [id:~/.dev/lprint] master(+40/-0)* 1 ± sudo lprint server -o server-name=127.0.0.1 -o server-port=8631
subcommand='server'
num_options=2
options[0].name='server-name', value='127.0.0.1'
options[1].name='server-port', value='8631'
num_files=0
F [2020-01-22T15:11:40Z] Unable to create IPv6 listener for 127.0.0.1:8631: Address family not supported by protocol
θ82° [id:~/.dev/lprint] master(+40/-0)* 1 ± 
```

Here is a syscall trace log (by prefixing `strace` to the cmdline)

https://gist.github.com/dreamcat4/ee83750b1f2eec6e850539b44f886ab0

this bit:

```sh
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 4
setsockopt(4, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(4, {sa_family=AF_INET, sin_port=htons(8631), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
listen(4, 5)                            = 0
fcntl(4, F_GETFD)                       = 0
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
socket(AF_INET6, SOCK_STREAM, IPPROTO_IP) = -1 EAFNOSUPPORT (Address family not supported by protocol)
```

**Comment by michaelrsweet** [comment]
Not sure what is going wrong here - it looks like IPv6 support is disabled completely on your system? Will attempt to duplicate.

**Comment by dreamcat4** [comment]
Yep its very likely is no IPV6... (in fact I am sure I cannot enable it) due to other dealbreaker issues with it such as the complete mess of dns resolvers on modern linux systems etc.

**Comment by dreamcat4** [comment]
To diable IPV6 stuff:

In `/etc/default/grub` add the kernel boot flag `ipv6.disable=1`

```sh
# disable ipv6 in kernel boot flags
GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1"
```

Then

```sh
sudo update-grub
sudo update-initramfs -c -k all
```

That should be it. If that didn't work, I also appended the line:  `precedence ::ffff:0:0/96 45'` in `/etc/gai.conf`. Not sure what else.

Cannot seem to find / grep anything else directly relevant with the string `ipv6` in my install log / notes. Probably just only the kernel flag should do it.

**Comment by michaelrsweet** [comment]
[master 467f6b4] Fix server mode when IPv6 listener cannot be created (Issue #12)
