### ISSUE TITLE
Dymo LW Multi-purpose labels 13x25mm

### ISSUE THREAD

**Issue by karlmag-no** [michaelrsweet/lprint#13]
Hi,
Just got aware of your project, and I am instantly in love with it, even before really having tested it (much), since I have multiple Dymo printers.

First issue I ran across is that I can't seem to see default support for the in title mentioned labels
(also see; https://www.dymo.com/en-GB/lw-multi-purpose-labels-13-x-25-mm-lw-multi-purpose-labels-1-2-in-x-1-in ) These where the ones loaded in the closest-at-hand lw-450 here.

While I guess I can define the label sizes myself using PWG, I'm still not quite sure how I would go about those since they are two labels side-by-side then next pair, etc.
(It's always annoyed me with those particular labels, since you will always waste one if you print an odd number of labels.)

But yeah.. how to handle those?

Thanks
KarlMag

**Comment by michaelrsweet** [comment]
So this particular label is actually 0.5x1in in North America (which makes sense from the odd metric dimensions): <https://www.dymo.com/en-US/view-all-labels/labelwriter-labels/lw-multi-purpose-labels-1-2-in-x-1-in>

But as you note this is a 2-up label so you use the 2-up size: 1x1in. The specific label size name for this is "oe_square-multipurpose-label_1x1in". I'll see about adding a note about this to the main documentation file...
