### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by milkman0007** [michaelrsweet/lprint#134]
Is there a version of LPrint that could run on an Android tablet? My idea is to run lprint  on an Android tablet with USB support, plug in my thermal printer via USB, and then let the tablet control the printer. I looked at Linux-based tablets, but they don’t seem to be as readily available on the secondhand market as cheap Android tablets. Also, if LPrint can not be  loaded on Android, what kind of undertaking would it be to have an Android version?

**Comment by michaelrsweet** [comment]
Sorry, no.

**Comment by michaelrsweet** [comment]
Oh, and it would be a complete rewrite of LPrint and PAPPL to maybe get something that would function on Android, and then it would function badly since you'd be running a server on a device that isn't meant for that usage. Not something I would like to do.

**Comment by milkman0007** [comment]
What do you think about sailfish or Ubuntu Touch os  installing on a tablet then running Lprint ?

**Comment by michaelrsweet** [comment]
I still don't see it as a good fit. I regularly use/recommend Raspberry Pi's (or similar devices) as print servers, but why use a device with a large display you don't need and limited USB support?
