### ISSUE TITLE
Choose media options listings either metric or non-metric?

### ISSUE THREAD

**Issue by karlmag-no** [michaelrsweet/lprint#14]
Hi,

When issuing

    `lprint options -d <printer>`

Would it be possible to get the sizes also defined/listed in metric sizes?
Maybe a way to globally (to lprint) choose one or the other as default?
I did look in the code and unless I am mistaken the sizes where only defined in inches, but also having them in metric might be a useful thing?
Personally I don't usually use inches, especially not fractional inches, so they are kind of confusing to be presented with.  I would imagine I'm not the only one. :-)

Thanks
KarlMag

**Comment by michaelrsweet** [comment]
@karlmag-no That's a good question - per the PWG media size standard, the sizes have to reflect the original media size definitions (which sadly are imperial units for most label sizes), but there is no reason I can't report the equivalent metric dimensions in the "options" output...
