### ISSUE TITLE
Issue printing with native Chrome dialog and with IPPS

### ISSUE THREAD

**Issue by markusdd** [michaelrsweet/lprint#145]
```
Mai 15 20:35:34 phantom-pc plasmashell[54257]: Warning: disabling flag --expose_wasm due to conflicting flags
Mai 15 20:36:20 phantom-pc cupsd[1805]: REQUEST localhost - - "POST /printers/Zebra-EPL-Page-Mode-4-inch-203dpi-Direct-Thermal HTTP/1.1" 200 530060 Print-Job successful-ok
Mai 15 20:36:20 phantom-pc lprint[51447]: I [2024-05-15T18:36:20.592Z] [Client 39] Accepted connection from '192.168.1.228'.
Mai 15 20:36:20 phantom-pc lprint[51447]: I [2024-05-15T18:36:20.592Z] [Client 39] HTTP_STATE_POST http://phantom-pc.local:8000/ipp/print/lprint_lp2844 HTTP/1.1 ()
Mai 15 20:36:20 phantom-pc lprint[51447]: I [2024-05-15T18:36:20.592Z] [Client 39] Continue
Mai 15 20:36:20 phantom-pc lprint[51447]: I [2024-05-15T18:36:20.592Z] [Client 39] Get-Printer-Attributes successful-ok
Mai 15 20:36:20 phantom-pc lprint[51447]: I [2024-05-15T18:36:20.592Z] [Client 39] OK application/ipp 1105
Mai 15 20:36:20 phantom-pc lprint[51447]: I [2024-05-15T18:36:20.593Z] [Client 39] HTTP_STATE_POST http://phantom-pc.local:8000/ipp/print/lprint_lp2844 HTTP/1.1 ()
Mai 15 20:36:20 phantom-pc lprint[51447]: I [2024-05-15T18:36:20.593Z] [Client 39] Continue
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
Mai 15 20:36:20 phantom-pc lprint[51447]: I [2024-05-15T18:36:20.593Z] [Client 39] Validate-Job client-error-attributes-or-values-not-supported (Unsupported print-color-mode keyword value.)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mai 15 20:36:20 phantom-pc lprint[51447]: I [2024-05-15T18:36:20.593Z] [Client 39] OK application/ipp 164
Mai 15 20:36:20 phantom-pc lprint[51447]: I [2024-05-15T18:36:20.593Z] [Client 39] Closing connection from '192.168.1.228'.
Mai 15 20:36:20 phantom-pc cupsd[1805]: [Job 55] Printer cannot print with supplied options.
Mai 15 20:36:20 phantom-pc cupsd[1805]: Zebra-EPL-Page-Mode-4-inch-203dpi-Direct-Thermal mkrause 55 [15/May/2024:20:36:20 +0200] total 1 - localhost Screenshot_20240515_011834.png (2984×1527)  -
Mai 15 20:36:20 phantom-pc cupsd[1805]: [Job 55] Backend ipp returned status 5 (cancel job)
```

I marked the relevant log line. Printing itself works beautifully on my LP2844, but when using the native Chrome dialog it fails probably because they send something unintelligible regarding color. Would it make sense to ignore this?

Second problem: I cannot use ipps on my machine (Nobara 39, which essentially is a latest greatest Fedora) because I get an error that the CUPS pki is invalid. When I modify the local connection address to just ipp it works. Is this expected?

EDIT: Firefox does not have the issue but they also list an explicit color setting which is set to black and white and can't be changed.

**Comment by michaelrsweet** [comment]
WRT "ignoring" unknown values, Print-Job and Create-Job will do so (assuming "ipp-attribute-fidelity" is false) but Validate-Job explicitly has to report unknown/unsupported/conflicting values or attributes (that's its purpose...)

Can you enable debug logging for LPrint (open web interface and toggle the log level in the View Log File page) and CUPS (`cupsctl --debug-logging`) and attach the logs to this issue?  That will help me determine where the problem lies.

WRT the PKI errors, again having debug logs would be useful.

**Comment by markusdd** [comment]
As for the Chrome issue, I switched back the printer to ipp protocol so that the connection works, and I have  attached the resulting logfile.

Here there is a lot more lprint debug output in there.
This issue exists with both printers (the Zebra LP2844 and the DYMO, Dymo example in the log).

[debug_chrome.log](https://github.com/michaelrsweet/lprint/files/15352001/debug_chrome.log)

**Comment by michaelrsweet** [comment]
Sorry for the long delay. The CUPS log indicates that Chrome is requesting a color print but (obviously) this printer can't do color.

It would be interesting to see what the CUPS PPD file contains (look in /etc/cups/ppd) but right now this doesn't look like an LPrint issue but a CUPS issue...
