### ISSUE TITLE
Support for the LabelRange LP620

### ISSUE THREAD

**Issue by Castone22** [michaelrsweet/lprint#147]
Drivers: https://www.labelrange.com/download/
Printer: https://www.labelrange.com/products/LP620/104.html

I am willing to get you an lp620 for testing purposes if necessary.

This issue is to start discussion around implementing an LP620 Driver for LPrint.  As far as i can tell, these printers don't seem to be compatible with the tspl generics, however they do seem to work partially under the zebra drivers, zpl_4inch-300dpi-dt, where they will only print half a page, when under version 1.1, the latest version just prints a blank page.

**Comment by michaelrsweet** [comment]
This printer appears to support ZPL, so have you tried the "Zebra ZPL 4-inch/300dpi/Direct-Thermal" driver ("zpl_4inch-300dpi-dt")?

**Comment by Castone22** [comment]
> This printer appears to support ZPL, so have you tried the "Zebra ZPL 4-inch/300dpi/Direct-Thermal" driver ("zpl_4inch-300dpi-dt")?

That looks like the same drvier i mentioned using in my initial statement.  in version 1.1 (the version in Debian 1:6.1.54-1+rpt2's repo) it did work printing half a page, in version 1.3.1 from the snap it just fails completely printing a blank page, after which the printer seems to completely forget how to line up a page until i restart it.

**Comment by michaelrsweet** [comment]
Actually, looking at the Mac driver and PPD, it is a TSPL2 printer so the driver you want to use is "tspl_300dpi".

**Comment by michaelrsweet** [comment]
And if you run:

```
lprint devices -o verbose
```

then I can add a listing for this specific model.
