### ISSUE TITLE
How to use proper/custom page size on Android/iOS/Windows?

### ISSUE THREAD

**Issue by ValdikSS** [michaelrsweet/lprint#149]
Not really an issue, but a question which may be useful for others as well.

I have XPrinter XP 365b label/recipient printer with 82 mm recipient paper installed. There's no IPP-defined media size for this width.

* Android: both [default print service](https://android.googlesource.com/platform//packages/services/BuiltInPrintService/+/refs/heads/android14-release/jni/ipphelper/ipphelper.c#77) and Mopria Print support only small subset of IPP defined media sizes. Mopria supports a bit more (A8, 4×4 inch and 3.5/3.5 inch, don't remember the name), but does not allow to set custom page size.  
Printed output is usually shifted horizontally and has large padding on top and bottom.
* iOS: supports more defined IPP media sizes, I could select any supplied by the PPD (2×4", 4×4", 4×6"), but not the custom one.  
4 inch is 100 cm, which is out of bounds of my paper, but it prints, also with large padding as the case in Android.
* Windows: basically the same as iOS. No method to use custom media size except with registry hacks as far as I know.

I also tried several label software on Android, neither supports IPP printing at all, only USB/Bluetooth/proprietary Wi-Fi connection is supported.

The only thing that worked reliably is printing on Linux from gimp. It allows to create custom media size, and it works fine.
Do you have any documentation, manuals, hints, software on how to use label printers shared over IPP using CUPS/LPrint?

**Comment by Siedlerchr** [comment]
I have a Windows 11 Insider ARM version from last September or similar, there custom paper sizes can be chosen correctly (I have an IPP server that announces complete custom sizes and one standard size). Can post a screenshot tomorrow. 

But not even in the latest Windows 11 releases, although it should theoretically include all features of that Insider Preview, from what I read, it's not working
