### ISSUE TITLE
Length for printer label

### ISSUE THREAD

**Issue by Magniveo** [michaelrsweet/lprint#155]
Hello, im built libcups, pappl and lprint. Where settings for length label? 
Im tried add work with format 54x60mm label but lprint printing without gap continues on current label, offset not helped.

**Comment by michaelrsweet** [comment]
LPrint supports custom label sizes, both as specified in your application's print dialog and in the web interface for LPrint.

It would help to know what versions are the various software you are using, what printer you are using, and what OS/Linux distribution.

**Comment by Magniveo** [comment]
Built last version for linux with changed new getCupsOption, with parameter enable usb, png in configure pappl, only lprint used. 
All okay only problem with length or height label. Im added parameters in code for zpl, all nice in webinterface showed 58 x 60 mm, 2 inch 203 dpi zpl driver. 
`lprint -d MyPrinter file.zpl`

**Comment by michaelrsweet** [comment]
You still haven't provided the versions of the software you are using...

Also, from the example you show, you are sending a (raw) ZPL file which will bypass ALL of the job options that you set in the web interface. The ZPL file needs to tell the printer what size label you are sending. There may also be configuration settings (label separator type, in particular) that you need to either provide in the ZPL file or set on the printer itself so it knows what you have loaded.

**Comment by Magniveo** [comment]
> You still haven't provided the versions of the software you are using...
> 
Software lprint, branch libcups3
