### ISSUE TITLE
Three 10 second delays while printing

### ISSUE THREAD

**Issue by gjanssens** [michaelrsweet/lprint#157]
Hi,

I am trying to get lprint to work in the following context:
* my labelprinter is a TSC model ML340P, connected over the network. It supports both TSPL and ZPL2 printer languages. I have configured it to use ZPL2
* I'm testing on a Fedora 39 system, using lprint 1.3.1
* The printer is set up via lprint's webinterface, using the appropriate ZPL2 driver (4in, 300dpi, thermal-transfer).

I can print labels on this printer by generating zpl command files and pass them to the printer via
lprint -d <printername> <zpl-file>

However printing each label takes about 30 seconds, while sending the same zpl file to the printer via a cups raw passthrough queue prints immediately.

I have no clue where to start to debug this unfortunately. I see the following in the lprint logs when I print a label:

```
nov 05 13:10:24 fedbox lprint[1325]: I [2024-11-05T12:10:24.812Z] [Client 69] Accepted connection from 'localhost'.
nov 05 13:10:24 fedbox lprint[1325]: I [2024-11-05T12:10:24.812Z] [Client 69] HTTP_STATE_POST http://localhost:0/ipp/print/TSCBureau1 HTTP/1.1 ()
nov 05 13:10:24 fedbox lprint[1325]: I [2024-11-05T12:10:24.812Z] [Client 69] Continue
nov 05 13:10:24 fedbox lprint[1325]: I [2024-11-05T12:10:24.812Z] Saving system state to '/var/lib/lprint.state'.
nov 05 13:10:34 fedbox lprint[1325]: I [2024-11-05T12:10:34.841Z] [Client 69] Get-Printer-Attributes successful-ok
nov 05 13:10:34 fedbox lprint[1325]: I [2024-11-05T12:10:34.841Z] [Client 69] OK application/ipp 14125
nov 05 13:10:34 fedbox lprint[1325]: I [2024-11-05T12:10:34.845Z] [Client 69] HTTP_STATE_POST http://localhost:0/ipp/print/TSCBureau1 HTTP/1.1 ()
nov 05 13:10:34 fedbox lprint[1325]: I [2024-11-05T12:10:34.845Z] [Client 69] Continue
nov 05 13:10:34 fedbox lprint[1325]: I [2024-11-05T12:10:34.845Z] [Job 12] Received 947 bytes of document data.
nov 05 13:10:34 fedbox lprint[1325]: I [2024-11-05T12:10:34.845Z] [Client 69] Print-Job successful-ok
nov 05 13:10:34 fedbox lprint[1325]: I [2024-11-05T12:10:34.845Z] [Job 12] Starting print job.
nov 05 13:10:34 fedbox lprint[1325]: I [2024-11-05T12:10:34.845Z] [Client 69] OK application/ipp 229
nov 05 13:10:34 fedbox lprint[1325]: I [2024-11-05T12:10:34.846Z] [Client 69] Closing connection from 'localhost'.
nov 05 13:10:54 fedbox lprint[1325]: I [2024-11-05T12:10:54.025Z] Saving system state to '/var/lib/lprint.state'.
nov 05 13:10:54 fedbox lprint[1325]: I [2024-11-05T12:10:54.884Z] [Job 12] Completed, job-impressions-completed=2.
```

Note the logs start at 13:10:24. After saving the system state, it waits 10 seconds before confirming a successfull call to Get-Printer-Attributes. Then it waits again after closing the connection from 'localhost'. The gap is now 20 seconds before anything is logged again. However the label is printed at 13:10:44 and the final log message appear only at 13:10:54.

What could be happening here and how to debug and solve this ? Thank you.

**Comment by michaelrsweet** [comment]
This sounds like the printer doesn't actually support all of ZPL (i.e. no status), so you really can't use the ZPL driver with LPrint for it.

Since this *is* a TSC label printer, probably better to use the TSPL driver instead (as it is the native language of the printer).

**Comment by gjanssens** [comment]
Ok thanks for the feedback. I'll see if I can rework our process to spit out TSPL labels.

Odd though that I don't have this issue when printing via cups using the passthrough raw queue. Is that because cups doesn't attempt to get status back ?

**Comment by michaelrsweet** [comment]
Correct, the CUPS driver is very limited while the LPrint driver is much more functional (assuming you are talking to a “real” ZPL printer…)
