### ISSUE TITLE
lprint can't see Dymo LabelWriter

### ISSUE THREAD

**Issue by jashephe** [michaelrsweet/lprint#16]
I have a Dymo LabelWriter 450 Twin Turbo hooked up to a Raspberry Pi 3 running Arch Linux (`Linux <hostname> 5.5.11-1-ARCH #1 SMP Sun Mar 22 07:43:38 MDT 2020 aarch64 GNU/Linux`).

When I start the lprint server via `lprint server`, and attempt to run `lprint devices`, no output is printed. However, if I run CUPS's `lpinfo -v`, I can see (amongst other lines) `direct usb://DYMO/LabelWriter%20450%20Twin%20Turbo?serial=12100803191925`.

I can add the printer with:
```
lprint add -d labelwriter -v "usb://DYMO/LabelWriter%20450%20Twin%20Turbo?serial=12100803191925" -m "dymo_lw-450-twin-turbo"
```
Upon attempting to send a print job, the server process logs the following:
```
[Printer labelwriter] Unable to open device 'usb://DYMO/LabelWriter%20450%20Twin%20Turbo?serial=12100803191925', pausing queue until printer becomes available.
```

I understand that aarch64 on the Raspberry Pi is a fairly unusual system to be running, but if you have any thoughts, I'd certainly appreciate them. I'm usually fairly comfortable but a little out of my depth in the printer domain, so apologies if this is lacking obvious debugging/diagnostics/etc. Happy to attempt any troubleshooting you might suggest.

### Several other observations...

- When I exit the `lprint server` process with Ctrl-C, I get the following:
```
I [2020-03-26T03:55:59Z] Shutting down main loop.
lprint: thread-watch.c:171: avahi_threaded_poll_lock: Assertion `p' failed.
fish: “lprint server” terminated by signal SIGABRT (Abort)
```
- If I try to remove the printer with `lprint delete -d labelwriter`, I get the following:
```
lprint: Unable to get information for 'labelwriter' - successful-ok
```
- If I add the printer to CUPS directly, I can print to it locally without too much trouble (although not remotely via IPP, although the error I'm getting there seems to be related to Dymo's `raster2dymolw`).

Last of all, just wanted to say thanks for developing this; it looks like there's been quite the back and forth over on apple/cups#5271, but just wanted to voice my support for your approach.

**Comment by michaelrsweet** [comment]
This sounds like a permissions issue - what are the permissions of the files under /dev/bus/usb?

Can you file separate issues for the other lprint observations? I've not personally seen either of them...

**Comment by jashephe** [comment]
Indeed, setting permissions seems to have done the trick. The printer has permissions of
```
crw-rw-r-- 1 root lp 189, 3 Mar 26 09:08 /dev/bus/usb/001/004
```
Adding the user account running lprint to the `lp` group did the trick. Thank you!

Still observing the other behavior; I'll open separate issues.
