### ISSUE TITLE
Can't remove printer with lprint delete

### ISSUE THREAD

**Issue by jashephe** [michaelrsweet/lprint#17]
When I try to delete a printer using `lprint delete`, a non-zero exit status is returned and the printer is not deleted.
```
$ lprint status
Running, idle since Thu, 26 Mar 2020 20:12:59 GMT
$ lprint printers
test-labelwriter
$ lprint delete -d test-labelwriter
lprint: Unable to get information for 'test-labelwriter' - successful-ok
<exit status=1>
$ lprint printers
test-labelwriter
```
Let me know if there's any other debugging information I can provide — thanks!

---
**Printer**: Dymo LabelWriter 450 Twin Turbo
**System**: `Linux <hostname> 5.5.11-1-ARCH #1 SMP Sun Mar 22 07:43:38 MDT 2020 aarch64 GNU/Linux`

**Comment by michaelrsweet** [comment]
Also applies to the "default" command... :/

**Comment by michaelrsweet** [comment]
[master 2c541b5] Fix `lprint default` and `lprint delete` (Issue #17)
