### ISSUE TITLE
List of compatible printers

### ISSUE THREAD

**Issue by LanceHaverkamp** [michaelrsweet/lprint#27]
Is there a list of compatible printers somewhere?

**Comment by slokhorst** [comment]
There's a list in [driver-common.c](https://github.com/michaelrsweet/lprint/blob/master/driver-common.c#L70). Basically the Dymo LabelWriter and Zebra ZPL printers, like the readme says.

**Comment by LanceHaverkamp** [comment]
Can't believe I read right past that, thanks! More caffeine for me, apparently.
