### ISSUE TITLE
LPrint API?

### ISSUE THREAD

**Issue by SonnyX** [michaelrsweet/lprint#28]
Is there any API through either lprint or through CUPS in order to add an label printer using the drivers from lprint application?

**Comment by michaelrsweet** [comment]
@SonnyX Yes, the CUPS API will let you send IPP Create-Printer (`IPP_OP_CREATE_PRINTER`) to the lprint server. You can use the "lprint-add.c" code as a template for your own implementation.

**Comment by SonnyX** [comment]
@michaelrsweet Thank you, I've implemented similar code to what's inside of `lprint-add.c`, is there also a way to get the available lprint drivers names and descriptions programmatically through cups?

**Comment by michaelrsweet** [comment]
@SonnyX You can do a Get-System-Attributes (`IPP_OP_GET_SYSTEM_ATTRIBUTES`) request to get the smi4699-device-command-supported attribute which lists the supported drivers.
