### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [michaelrsweet/lprint#30]
I would like to point out that an identifier like “[`_LPRINT_H_`](https://github.com/michaelrsweet/lprint/blob/c37c5dc0f75521668d753913b66e508ce222ab9a/lprint.h#L11 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by michaelrsweet** [comment]
@elfring I will consider it for this project since it isn’t a library.

**Comment by michaelrsweet** [comment]
fixed

**Comment by elfring** [comment]
Thanks for [your adjustment of an affected include guard](https://github.com/michaelrsweet/lprint/commit/58e246b1e6ebf0aa674e8033ff5e469c6c539ebc#diff-f90c6a112a354f97b7f61d8e73708093cd2abf1a69cd0c6d31e2b9670fe0529eL11 "Software updates").
