### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [michaelrsweet/lprint#31]
Would you like to add more error handling for return values from functions like the following?
- [pthread_rwlock_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_rwlock_init.html "Initialize a lock.") ⇒ [lprintCreateSystem](https://github.com/michaelrsweet/lprint/blob/c37c5dc0f75521668d753913b66e508ce222ab9a/server-system.c#L65)
- [strdup](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [lprintCreatePrinter](https://github.com/michaelrsweet/lprint/blob/c37c5dc0f75521668d753913b66e508ce222ab9a/server-printer.c#L280)

**Comment by michaelrsweet** [comment]
@elfring All of this code will be going away once I complete the switchover to PAPPL.
