### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [michaelrsweet/lprint#32]
[An extra null pointer check is not needed](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") in [the function “lprintDeleteJob”](https://github.com/michaelrsweet/lprint/blob/c37c5dc0f75521668d753913b66e508ce222ab9a/server-job.c#L291 "Update candidate").

**Comment by michaelrsweet** [comment]
All this code is gone now, and PAPPL has replaced it.
