### ISSUE TITLE
no macOS disk image is present in the source distribution

### ISSUE THREAD

**Issue by tarikjn** [michaelrsweet/lprint#33]
Just getting to know lprint and looking at the installation doc:

> A disk image is included with all source releases on Github for use on macOS 10.14 and higher.

But no disk image is present in the source distribution (expecting `.dmg`, `.img` etc.)

PS: thank you for the amazing work on lprint/pappl/cups

**Comment by michaelrsweet** [comment]
Hmm, OK well I'm gearing up to do a 1.1 release in the nearish future, so I will make sure to provide a DMG for that release...

**Comment by tarikjn** [comment]
Thank you! Even better would be generating it as a distribution image. Happy to do a PR for it, though it might take me a while to find some free time and get familiar with the build scripts. Could be just dropped manually as a binary on the Github project release for now + doc update on where to find it.

**Comment by jphansendk** [comment]
Just curious.. How far away are we from the 1.1 release? :-)
I'm just too stupid to install it via terminal :-/

**Comment by michaelrsweet** [comment]
@jphansendk Not too far, I got the initial porting work done to use PAPPL and just need to fix some bugs...

**Comment by michaelrsweet** [comment]
@tarikjn @jphansendk Apologies for the long delay, finally got PAPPL 1.1 out the door and now am testing for a 1.1 release of LPrint. Here is a ZIP with a beta binary, signed and notarized so you shouldn't get any security warnings aside from the usual "you downloaded this do you want to run it" dialog...

[lprint-1.1-20211217-macos.zip](https://github.com/michaelrsweet/lprint/files/7736961/lprint-1.1-20211217-macos.zip)

**Comment by jphansendk** [comment]
I will test it when I'm back at the office. Maybe Monday if the government decides we can leave to work... Damn corona

**Comment by michaelrsweet** [comment]
New release actually includes an installable package (installs to /usr/local) with a launchd plist to start it on boot.

**Comment by jphansendk** [comment]
Sorry.. I'm just to dump to understand how to install this 🤯

**Comment by michaelrsweet** [comment]
@jphansendk Just download the .pkg file and open it. The macOS installer will open and guide you through it.

**Comment by jphansendk** [comment]
Doh.. Didn't see a dmg.. Sorry 😏
