### ISSUE TITLE
Support for Zebra EPL2 Printers requested. 

### ISSUE THREAD

**Issue by brianbarr** [michaelrsweet/lprint#38]
There are a zillion Zebra 2844 printers out there that do not support ZPL .. they use EPL2. 

I use 5 of them for printing USPS and Fedex labels. 

Could you add support for EPL2 in the upcoming 1.1 release? 

It appears some of the supporting code for EPL2 support is already in there.

**Comment by michaelrsweet** [comment]
@brianbarr I'll see if I can get this added for the 1.1 release...

**Comment by adamdport** [comment]
@michaelrsweet do you have any idea when that 1.1 release might be?

**Comment by michaelrsweet** [comment]
@adamdport Hopefully soon. Been wrapping up a couple of other projects for customers so I haven't had a lot of extra time lately...

**Comment by michaelrsweet** [comment]
[master 5bd64a0] Add EPL2 driver (Issue #38)
