### ISSUE TITLE
How do I uninstall?

### ISSUE THREAD

**Issue by adamdport** [michaelrsweet/lprint#39]
I'm new and have been boxing with getting settings right. After failing several times, I tried deleting my botched device/jobs but I can't due to #17. Since that's resolved and on master, I tried building from master instead, but that errored out since it requires PAPPL. Is there a simple way to just delete everything I've installed/configured and start over? Thanks.

**Comment by michaelrsweet** [comment]
@adamdport You just need to remove `/usr/local/bin/lprint` (or `/usr/bin` if you pointed it there), the `lprint*` man pages in `/usr/local/share/man/*/lprint*`, and the `~/.lprintrc` file.
