### ISSUE TITLE
Unable to list devices on ubuntu 18.04

### ISSUE THREAD

**Issue by mcss86** [michaelrsweet/lprint#41]
Installed via snap, @Precision-:~/Downloads$ sudo lprint devices
lprint: Unable to initialize USB access: Other error

**Comment by mcss86** [comment]
Also attempting to force add a printer and print is triggering apparmor
Jul 29 14:38:02 Precision kernel: [  538.901201] audit: type=1400 audit(1627583882.116:26): apparmor="DENIED" operation="open" profile="snap.lprint.lprint" name="/home/user/Downloads/1e5eac8db404407e8d13cce080fb2be0.zpl" pid=5253 comm="lprint" requested_mask="r" denied_mask="r" fsuid=0 ouid=1000

**Comment by michaelrsweet** [comment]
This sounds like something is wrong with snapd’s mapping of the lprint interface permissions. I’ve been working on getting the new PAPPL-based lprint finished up but will see if I can reproduce this on my Ubuntu laptop…

**Comment by michaelrsweet** [comment]
@mcss86 OK, I've promoted the current snap build to beta - please try installing the update lprint 1.1 and let me know what happens.

**Comment by mcss86** [comment]
Hey man,
I've installed the update and now built pappl, but im having NIGHTMARES
getting pappl libraries in the correct places to run properly.  Suggestions
for make commands to fix this?
@Precision-T1700-32g:~$ lprint
/snap/lprint/206/usr/local/bin/lprint: error while loading shared
libraries: libpappl.so.1: cannot open shared object file: No such file or
directory

**Comment by michaelrsweet** [comment]
@mcss86 The PAPPL shared library is part of the snap, although it looks like it isn't getting picked up by the run-time linker for some reason. Investigating...

**Comment by brianbarr** [comment]
running "snap connect lprint:raw-usb"  after lprint install  - may fix this

**Comment by mcss86** [comment]
That did help but now apparmor is in the way :

***@***.***:/home/bt/Downloads# lprint -d labelprinter ./test.zpl
lprint: Unable to print './test.zpl': Permission denied
***@***.***:/home/bt/Downloads# tail /var/log/syslog
an 20 02:26:10 Precision-T1700-32g systemd[4827]: Started
snap.lprint.lprint.4c063460-ae28-4ebe-875e-fee964e1765b.scope.
Jan 20 02:26:10 Precision-T1700-32g kernel: [  571.310797] audit: type=1400
audit(1642663570.024:21): apparmor="DENIED" operation="open"
profile="snap.lprint.lprint" name="/home/btaublib/Downloads/test.zpl"
pid=8178 comm="lprint" requested_mask="r" denied_mask="r" fsuid=0 ouid=1000

**Comment by michaelrsweet** [comment]
@mcss86 What happens if you try doing:

```
snap connect lprint:home
```

???

**Comment by mcss86** [comment]
Same apparmor="Denied"

**Comment by mcss86** [comment]
This might also be of note:
***@***.***:/home/btaublib/Downloads# lprint add -d
labelprinter -v usb://UPS%20/Thermal%202844%20 -m zpl_4inch-203dpi-dt
lprint: statefile='/var/snap/lprint/211/lprint.conf'
E [2022-01-20T07:24:30.615Z] Unable to register system, is the Avahi daemon
running?
