### ISSUE TITLE
Save server configuration & start as daemon

### ISSUE THREAD

**Issue by CyrosX** [michaelrsweet/lprint#42]
Dear michaelrsweet,

Thanks for your hard work!
I have some questions regarding the server mode.
What I want to achieve is making a Dymo 450 Duo available to a 
cups server on another server (same network).
This works, but there is a problem.

"lprint server -o server-port=8631 -o server-name=dietpi &"
I'm using this command as an autostart on a Raspberry Pi Zero W with DietPi.

So my questions are:
Is there another way of "daemonizing" the server?
I've installed the package with apt. lib-cups and some other needed packages were installed,
but no full cups.
Is there another auth-server than cups, which can be used? Maybe system users?

--
Also I cannot modify the printers. :'(
We're using yellow DYMO D1 as tape (12x7000mm) and white LW Adress Labels (36x89mm) as labels (dymo-450-label)

user@DietPi:~# lprint modify -d dymo-450-tape -o print-content-optimize=text
lprint: Unable to modify printer - Unsupported print-content-optimize-mode-default keyword value.

**Comment by michaelrsweet** [comment]
@CyrosX You can actually setup a systemd service file to run the server command and collect the logs via stderr ("-o log-file=-").

As for an auth-server, I'm not sure what you mean? What are you trying to do with authentication?

WRT modifying printers, what version of LPrint are you using - my last release or the current Git code? The "print-content-optimize" option really doesn't do anything for the Dymo printers, but you should be able to set any supported value as the default...

**Comment by michaelrsweet** [comment]
@CyrosX Sorry for the delay in responding - what do you mean by "negative pages"?

I'm getting ready to release v1.1, which requires PAPPL (recently released v1.1.0) and might fix some of the issues you are seeing.

On macOS clients, they should see the printer as AirPrint and be able to use it directly without needing to manually add it. But regardless the print options will be different from the DYMO driver which uses a bunch of non-standard options and values...

**Comment by michaelrsweet** [comment]
@CyrosX Please file a new if you still have problems with v1.1...
