### ISSUE TITLE
Code signature problems: dyld: Library not loaded: /usr/local/lib/libpappl.1.dylib

### ISSUE THREAD

**Issue by erikwahlstrom1** [michaelrsweet/lprint#43]
Hi Michael!

I'm getting this error running lprint:

dyld: Library not loaded: /usr/local/lib/libpappl.1.dylib
  Referenced from: /usr/local/bin/lprint
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libpappl.1.dylib: code signature in (/usr/local/lib/libpappl.1.dylib) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
zsh: abort      lprint

OSX: 11.6

Latest github-rep for lprint is used - no problems running .configure, and make is with no errors.

pappl-1.0.3 is used, no problems with .configure and make is with no errors.

Any clue?

Best wishes,
Erik

**Comment by michaelrsweet** [comment]
@erikwahlstrom1 I've been testing against PAPPL 1.1 which has some API changes/fixes.

**Comment by michaelrsweet** [comment]
@erikwahlstrom1 Please try the PAPPL 1.1.0 release with current Github sources. I will also be doing a release soon with binaries for macOS...
