### ISSUE TITLE
systemd service file in wrong directory

### ISSUE THREAD

**Issue by alteholz** [michaelrsweet/lprint#51]
When preparing the Debian package of lprint, lintian complains:
 E: lprint: systemd-service-file-outside-lib etc/systemd/system/lprint.service
 N:
 N:   The package ships a systemd service file outside /lib/systemd/system/
 N:
 N:   Systemd in Debian searches for unit files in /lib/systemd/system/ and
 N:   /etc/systemd/system. Notably, it does *not* look in
 N:   /usr/lib/systemd/system/ for service files.
 N:
 N:   System administrators should have the possibility to overwrite a
 N:   service file (or parts of it, in newer systemd versions) by placing a
 N:   file in /etc/systemd/system, so the canonical location used for
 N:   service files is /lib/systemd/system/.

Do you mind changing the directory of the service file to /lib/systemd/system?

  Thorsten

**Comment by zdohnal** [comment]
Hi @alteholz ,

I have PR #50 for tackling this - currently with solution to use ```%{prefix}/lib/systemd/system``` by default, but you can pass a path on your own. The prefix is usually set by passing ```--prefix``` to configuration script, or ```/usr/local``` by default.
