### ISSUE TITLE
Support for TSPL Printers

### ISSUE THREAD

**Issue by GravisZro** [michaelrsweet/lprint#54]
I would like to see the support added for TSPL.  TSPL was expanded it to TSPL2 and TSPL put out a [massive manual](https://kubesail.com/blog-images/blog-printer-tspl.pdf) but only TSPL is needed since it has a `BITMAP` command.  Other companies [use TSPL and have manuals](https://www.meto.com/metoprint/files/meto_print_programming_manual_tspl_ez_en.pdf) which may mean they are using TSC components or they re-implemented the language.

Someone actually wrote an [image to TSPL converter in javascript](https://github.com/kubesail/raster-to-tspl-js/blob/main/print.js) but it's really just sending this:
```
\r\nSIZE `label width` mm, `label height` mm
\r\nSET TEAR ON
\r\nSET CUTTER OFF
\r\nSET PEEL OFF
\r\nDENSITY `darkness`
\r\nCLS
\r\nBITMAP 0,0,`bitmap width`,`bitmap height`,1, `1-bit image data`
\r\nPRINT 1,1
\r\n
```

If you _really_ wanted, you could send a raw raster data and make a program in TSPL to decode it.  However, I'm pretty sure that could be done with ZPL and you didn't do that.

**Comment by michaelrsweet** [comment]
@GravisZro What specific printers do you want to support with this?

**Comment by GravisZro** [comment]
I don't have any specific model in mind but TSC has like 90 different label printers that all support TSPL.

**Comment by proski** [comment]
I considered adding support for Munbyn ITPP941, a TSPL printer, in #36 but got a reply that it won't be merged for legal reasons. I never started coding the change for LPrint. But I made a patch for rastertolabel, I use that code every day: https://github.com/proski/cups/commit/9ade138db4387ed016f70feb11a3b7a05daf04ca

**Comment by GravisZro** [comment]
@proski 
I would say just create a generic TSPL driver for LPrint and add all the known legitimate TSPL printers.  If it's really a knockoff then it should be detected as one of the legitimate printers.

**Comment by michaelrsweet** [comment]
Initial check-in:

[master 2a72220] Start adding new drivers; initial TSPL driver.

**Comment by michaelrsweet** [comment]
Looks like there may be some issues (#113) but the basic driver is now in place. Closing.
