### ISSUE TITLE
Support for Seiko Smart Label Printers

### ISSUE THREAD

**Issue by tbowent** [michaelrsweet/lprint#58]
Many of these printers are not supported by cups (pre-SLP 100 models) but are readily available and quite serviceable but do not have driver support.  Error handling in CUPS is lacking (wrong labels loaded etc.).  Slap had support for these printers, but it is a command line only solution, not really suitable for end users and does not support newer models (post-SLP 240 models).  Thank you for you consideration.  Thanks and cheers.

**Comment by michaelrsweet** [comment]
@tbowent I'm not sure there is any documentation for their older label printers, although I was able to find the current Linux driver they provide that covers the SLP-100 and later models. Short of having documentation and/or a printer to test with, I'm not sure what I can do. I *will* investigate supporting the same printers as the Seiko Linux driver at least.

**Comment by michaelrsweet** [comment]
[Linux drivers](https://siibusinessproducts.com/support/linux-software-and-drivers/)

**Comment by tbowent** [comment]
Thanks, so much for the reply.   I am aware of drivers referenced below, but no support for Plus, EZ30, Pro, 120, 220, 410, 420, 430. I am looking at creating drivers for these models (hopefully reworking some of the existing drivers), but this is beyond my ability at this time.  Thanks for taking the time to find the link and reply.  Cheers.

**Comment by tbowent** [comment]
Thanks so much for giving this consideration.  There are many of these units still in the wild.  I'm a big fan of these (simple and reliable) and have hoarded much documentation over the years (including SDK doc).  Please reach out should you be interested. Always happy to share.  

Sorry, the comment I made about post- SLP 240 support was regarding Mac driver support (typing faster than I was thinking). Not sure how to go about compiling the linux drivers in Mac OS Catalina.

**Comment by michaelrsweet** [comment]
The Linux driver supports the SLP 100, 200, 240, 410, 420, 430, 440, 450, 620, 650, and 650SE.

**Comment by tbowent** [comment]
That is great news!  I downloaded and compiled for Debain 10 (using Daniel Oneil's githab offering https://github.com/danieloneill/SeikoSLPLinuxDriver) and it is working with Seiko SII SLP 240.

**Comment by michaelrsweet** [comment]
[master 083bc8e] Initial SEIKO printer driver (Issue #58)

Since I don't have one of these printers in my office, can somebody please test this?

**Comment by tbowent** [comment]
I’m off Work December 08 -15.  I’ll have a look.  Thanks and Cheers.

**Comment by michaelrsweet** [comment]
OK, I got a SLP-650 to test with and all seems to be working with the following changes:

[master 4afcb33] Finalize SLP driver (Issue #58)

Some notes on the implementation:

- The advertised label sizes reflect the printable area (per the CUPS driver usage) and not the marketing size, e.g., the 36x89mm large shipping label is reported as 35x83mm. All labels have 0.5mm left/right and 3mm top/bottom margins. Ideally we should be reporting the actual label dimensions and using the margins for the output. *Holler in the comments below if you'd like to see this change...*
- These printers don't support status reporting of any kind despite having a status command defined (0x01). The USB Get-Status values are also wrong - the printer always says its cover is open and it is out of media/labels...
