### ISSUE TITLE
Unable to start server: Bad file descriptor

### ISSUE THREAD

**Issue by GatCode** [michaelrsweet/lprint#59]
Hi,
I am running MacOS 12.2.1 and downloaded your prebuilt .pkg (v1.1.0) from the releases page and I am unable to add a new printer. If I run the add command, I always get the following error:

```
❯ lprint add -d ZebraLP2844 -v socket://192.168.111.76 -m epl2_4inch-203dpi-dt
lprint: Unable to start server: Bad file descriptor
```

Can you help me out? Thanks!

**Comment by ILXDan** [comment]
MacOS 12.3.1 here, getting the exact same error message on the prebuilt pkg.

**Comment by michaelrsweet** [comment]
So I just tested this with current lprint and PAPPL code and it is working. I will be posting updated binaries in the near future.

**Comment by GatCode** [comment]
> So I just tested this with current lprint and PAPPL code and it is working. I will be posting updated binaries in the near future.

Thank you very much! The updated binaries would be very helpful!

**Comment by lanewinfield** [comment]
I'm having this issue as well. I'm running 15.2. Seems I have to reinstall the pkg after restarting to keep it working.
