### ISSUE TITLE
Support for Configuring/Saving Custom Label Sizes

### ISSUE THREAD

**Issue by joerggollnick** [michaelrsweet/lprint#61]
I like to define some custom label sizes for a ZPL printer.
My understanding, all media options are predefined in lpirnt-zpl.c as lprint_zpl_2inch_media respective lprint_zpl_4inch_media.
I like to define something like om_label_100x150mm or om_label_40x25mm?
It would be nice, if somebody can point me in right direction, where to change it in addition?
Thanks in advance

**Comment by michaelrsweet** [comment]
@joerggollnick The current code advertises custom label size support, so you should be able to define custom label sizes in the print or page setup dialogs.

In the LPrint code, you can add additional strings to the corresponding lists in lprint-zpl.c. I'll also track this for a future LPrint update to add a web interface for extending the media list to include custom sizes.

**Comment by michaelrsweet** [comment]
The current code tracks a single custom size per source.
