### ISSUE TITLE
Documentation Request - What is the minimum required MacOS version that supports a lprint server installation ? 

### ISSUE THREAD

**Issue by brianbarr** [michaelrsweet/lprint#66]
What is the minimum required MacOS version that supports a lprint server installation ? That is not clear from the docs. The docs specify that a  MacOS 10.8.x can utilize lprint as a client ... what about as a server?

**Comment by michaelrsweet** [comment]
@brianbarr The binaries I produce are for 10.14 and later. Doing earlier than that is hard from a code signing perspective (changes that are not backwards compatible) and for some libcups features that depend on newer macOS releases. And I no longer have hardware that will run older macOS releases so no way for me to test/build. Running on older macOS releases is technically possible but you'll definitely need to use a custom build of libcups.

I'll make sure the next LPrint release documents the supported macOS versions for my binaries.

**Comment by michaelrsweet** [comment]
Documentation now says:

> A package file is included with all source releases on Github for use on macOS
> 10.14 and higher for both Intel and Apple Silicon.
