### ISSUE TITLE
lprint devices: the call to libusb_claim_interface() fails silently with no error message

### ISSUE THREAD

**Issue by dreamcat4** [michaelrsweet/lprint#7]
Hey there. Today is the first time I have compiled and ran your great new program, Unfortunately there seems to be some kind of an issue because the USB device is already in use or 'claimed' here on ubuntu. Despite me having power cycled it. And having deleted the existing printer entries for it in CUPS.

What appears on the screen after plugging the USB back in is 'adding printer...' etc. And then gnome or the OS is automatically re-adding the detected printer back in as some generic text printer device.

So then later on when I am calling your program here `lprint devices` I have enabled the debug trace logging and added my own trace lines. And I can see it successfully enumerates over all the connected usb devices and finds my label printer.

At this exact point in the code it tries to claim the printer and silently fails because the usb device is already 'claimed' which I assume simply means that it is already in use by another host program.

As a consequence of this the `device` pointer gets set to NULL and the rest of the routine falls through to the next unknown usb device being enumerated in the loop. Nothing is printed to stdout so there is no program output whatsoever.

Thing is... isn't that a pretty common scenario ? I have been reading [here on stack](https://stackoverflow.com/a/6476253) that it might require a call to `libusb_detach_kernel_driver()` first of all in order to free up the device? That call is nowhere in your code ATM.

Or is there a different bug going on here? Or some other thing I am missing / should be doing elsewhere on the system (for example in udev, to stop the printer being grabbed by the system automatically).

Any help appreciated. Thank you. Just want to get a little bit further so we can assess how different this printer of mine is / if it can work under the existing Zebra driver or needs an entirely new driver for the other `TSPL2` printer language.

**Comment by michaelrsweet** [comment]
Sigh, it amazes me that Linux distributions still ship the usblp module - it has been deprecated for over 10 years and is known not to work with many printers...

[master 12002e6] Detect busted usblp kernel driver as needed (Issue #7)

**Comment by dreamcat4** [comment]
This worked. Thank you for fixing tit However it turns out there is another little wrinkle here around this same command, which I shall open as a separate issue.
