### ISSUE TITLE
How to setup CUPS to use lprint server ?

### ISSUE THREAD

**Issue by Oberonc** [michaelrsweet/lprint#73]
Hi

I manage to print a test page using the web interface and now I want to simply print a "hello world" from gedit.
For that I need to setup lprint in CUPS.
I figured that lprint supports ipp (The debug log has the following line in it: "Printer 'Zebra ZD420' at resource path '/ipp/print/Zebra_ZD420'.")
I try to add my printer (Zebra ZD420) using the following url - "ipp://localhost/ipp/print/Zebra_ZD420"
.. and nothing happens when I try to print (I just see the job pending)

**Comment by michaelrsweet** [comment]
You need to include the port number - typically 8000 on Linux but lprint should be logging it...

**Comment by Oberonc** [comment]
> You need to include the port number - typically 8000 on Linux but lprint should be logging it...

Would make sense and be helpful if you add a few lines about this to the documentation.

**Comment by michaelrsweet** [comment]
@Oberonc Normally the printer will just show up (be discovered) and you can pick it (if it isn't auto-added by cups-browsed). I can't document every Linux distribution's way of supporting things, unfortunately...
