### ISSUE TITLE
IPP Everywhere generic CUPS driver doesnt work with lprint

### ISSUE THREAD

**Issue by Oberonc** [michaelrsweet/lprint#74]
Test page is printed successfully from the web interface of lprint.
a PNG file is printed successfully from the command line using lprint.

Printer: Zebra ZD420
OS: Ubuntu 20.04 LTS
PAPPL: 1.2.1 (latest release)
lprint: latest from git

When I add IPP Everywhere generic driver I encounter 2 problems:
1. After adding the printer when I try to print a test page it crashes (I run it again with valgrind for extrq information)
[valgrind.txt](https://github.com/michaelrsweet/lprint/files/9358898/valgrind.txt)
2. When I try to print a PNG file using CUPS (same PNG that can be printed using command line lprint) I get an error:
[badrequest.txt](https://github.com/michaelrsweet/lprint/files/9358903/badrequest.txt)

**Comment by michaelrsweet** [comment]
Can you attach the locally-generated PPD file from your system? This obviously should not crash but the CUPS side is sending a 4961x7016 bitmap instead of the expected 456x429.

**Comment by michaelrsweet** [comment]
Closing; please re-test and if the problem still occurs then attach the PPD file from /etc/cups/ppd.
