### ISSUE TITLE
Darkness setting doesn't work, Zebra dithering.

### ISSUE THREAD

**Issue by ersan** [michaelrsweet/lprint#76]
I have a Zebra LP2844 EPL printer, fought with setting up lprint and finally got it working.  Even compiled the current git versions of lprint/pappl to be sure.

The darkness setting doesn't appear to work at all, it doesn't matter if it's 0% or 100% it prints the same - extremely light and not readable.  Doesn't matter what client I print it from either.

![printing-defaults](https://user-images.githubusercontent.com/262119/187911139-65788c12-5edf-41a1-82b5-e90e40acc166.png)

![IMG_2640](https://user-images.githubusercontent.com/262119/187911154-6883c762-c7a6-43e0-831e-2554102c66b7.jpg)

Also I was hoping to use lprint because of a [dithering problem](https://github.com/apple/cups/issues/5092) that plagues cups - but there don't seem to be any dithering settings here and it has the exact same issue as you can see in the printout.

Some other small things I noticed:
- All of your printer driver descriptions say ZPL even if they are EPL drivers (e.g. epl2_4inch-300dpi-dt "Zebra ZPL 4-inch/300dpi/Direct-Thermal" "") which makes selecting drivers from the web UI confusing.
- Your [documentation](https://www.msweet.org/lprint/lprint.html) for "lprint modify" has a -D switch that should be -d
- Also in the documentation the "Server Web Interface" section at the bottom omits the "server" part of the command

**Comment by ersan** [comment]
I see [this comment](https://github.com/OpenPrinting/cups-filters/issues/221#issuecomment-614267049) about using `-o print-color-mode=bi-level` - but when I do that I get `Unsupported print-color-mode-default=bi-level(0x0004)`

**Comment by brianbarr** [comment]
This issue has persisted for literally years. Fixing the Zebra Cups drivers to eliminate this long standing defect was abandoned several years ago in favor of this ahh.... new solution. While the architecture of LPRINT, PAPPL, et al is very impressive it still fails to fix a basic issue -- that Linux and Mac users still cannot print clearly rendered basic barcodes on Zebra printers. Using Windows or an expensive 3rd party driver is the only thing that actually works. Perhaps one day..

**Comment by michaelrsweet** [comment]
OK, so looking at this, the EPL driver is sending a darkness command to the printer. I don't have an old 2844 to test with, but a newer printer using EPL emulation seems to work with it...

I will try to address any documentation issues (lots of stuff all mixed up here...)

WRT print-color-mode=bi-level, that was an omission in the capabilities:

[master 2fce253] Fix missing print-color-mode=bi-level (Issue #76)

**Comment by michaelrsweet** [comment]
[master 0baa93e] Fix docos (Issue #76)
