### ISSUE TITLE
suggestion(s) for lprint devices when: nothing, no error message is printed as regular user, but works as superuser

### ISSUE THREAD

**Issue by dreamcat4** [michaelrsweet/lprint#8]
Just a small matter. Not sure really which of these solution(s) you might prefer. It's just some suggestions to help for other users in case they encounter a similar difficulty.

When I ran the subcomand `lprint devices` without superuser privileges, then nothing was printed as the program output.

I could see in the extra debug logging that this call was failling to [`libusb_open()`](https://github.com/michaelrsweet/lprint/blob/master/device.c#L467)

To solve this problem, at least for my ubuntu linux system here. I realized that the following very specific udev rule needed to be added for my printer:

```sh
$ cat /etc/udev/rules.d/xprinter-xp-460b.rules 
# udev rules for xprinter xp-460b thermal label printer 4x6 inches
SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTR{idVendor}=="2d37", ATTR{idProduct}=="4296", MODE="0666"
```

This then granted the needed permissions to allow the call to [`libusb_open()`](https://github.com/michaelrsweet/lprint/blob/master/device.c#L467) to succeed. Otherwise that point in the code will fail silently and fall through. With no indication as to the reason for why nothing is detected.

The other alternative option was to run `lprint` as root user. Which also worked just fine. However being that libusb is a userland service perhaps some people would prefer to run it as such. Without elevating permissions? So maybe the udev rule seems like a better idea. IDK.

Perhaps printing out a suitable warning message would be helpful. If it is possible to determine the most likely reason for the failed call to `libusb_open()`. So that the regular user who is not technically inclined can be made aware and know how to resolve the issue. I.e. that they need to either run `lprint` as the root user, or otherwise modify their udev rules by adding an appropriate entry. Perhaps even more help is to report the matched (but failed) usb device vendor id and product id. Then that is enough information for a user how to modify their udev rules to allow that type of a device through.

Another possible solution is to just install all of the udev rules at the packaging level (snap or whatever distro). That ensures the `lprint` program can always have permission to access all of the printers which it knows it supports.

Another way would be to include an explanation as troubleshooting steps in the documentation or FAQ. Well whatever! At least you have a bug report about it now.

**Comment by michaelrsweet** [comment]
One of the changes I'll be making for the next beta is to report the libusb error messages to the console or log file, as appropriate. Unfortunately, the permissions needed for a raw USB access vary wildly between the various Linux distros so it will be hard to normalize any directions for this... :/

**Comment by michaelrsweet** [comment]
[master 0d270b9] Add error logging for device accesses (Issue #8)
