### ISSUE TITLE
Support for DYMO 550 turbo

### ISSUE THREAD

**Issue by stepanselyuk** [michaelrsweet/lprint#86]
Hello,
I cannot find the driver among supported drivers using `lprint drivers` and it is commented out in the code.
Does lprint support DYMO 550 series?

**Comment by michaelrsweet** [comment]
No, the 550 series uses a new command set (same as the LabelWriter Wireless) and needs a new driver, which is being tracked by issue #23. Fortunately DYMO is providing documentation so it will eventually get added.

**Comment by stepanselyuk** [comment]
Just for history: I found the support for 550 Turbo there https://github.com/computerlyrik/dymoprint
