### ISSUE TITLE
can't seem to set certain printer options

### ISSUE THREAD

**Issue by dreamcat4** [michaelrsweet/lprint#9]
Hi again,
So continuing on from issue #6. I am testing / trying to use lprint with my `xprinter xp-460b` with the driver named `zpl_4inch-203dpi-dt`. Because that is the only one of the Zebra devices which seems to generally match my printer.

However it's not feeding right, and flashing after 1 print (as if the feeding is broken). And it only prints out the first 4 inches of the print.

Anyhow I wanted to try setting some of these printer options. In the hopes that it will then make the feeding work better etc. And maybe resolve some of these issues. Unfortunately this is not something that is working for me yet. And I'm not really sure why.

Here is the full list of print options I see getting reported back to me when i query `lprint option`

```sh
$ lprint options
Print job options:
  -n COPIES
  -o media=oe_4x6-label_4x6in (default)
  -o media=oe_1.25x0.25-label_1.25x0.25in
  -o media=oe_1.25x2.25-label_1.25x2.25in
  -o media=oe_1.5x0.25-label_1.5x0.25in
  -o media=oe_1.5x0.5-label_1.5x0.5in
  -o media=oe_1.5x1-label_1.5x1in
  -o media=oe_1.5x2-label_1.5x2in
  -o media=oe_2x0.37-label_2x0.37in
  -o media=oe_2x0.5-label_2x0.5in
  -o media=oe_2x1-label_2x1in
  -o media=oe_2x1.25-label_2x1.25in
  -o media=oe_2x2-label_2x2in
  -o media=oe_2x3-label_2x3in
  -o media=oe_2x4-label_2x4in
  -o media=oe_2x5.5-label_2x5.5in
  -o media=oe_2.25x0.5-label_2.25xin
  -o media=oe_2.25x1.25-label_2.25xin
  -o media=oe_30859-paint-can-label_2.25x3.125in
  -o media=oe_2.25x4-label_2.25x4in
  -o media=oe_2.25x5.5-label_2.25x5.5in
  -o media=oe_2.38x5.5-label_2.38x5.5in
  -o media=oe_2.5x1-label_2.5x1in
  -o media=oe_2.5x2-label_2.5x2in
  -o media=oe_2.75x1.25-label_2.75x1.25in
  -o media=oe_2.9x1-label_2.9x1in
  -o media=oe_3x1-label_3x1in
  -o media=oe_3x1.25-label_3x1.25in
  -o media=oe_3x2-label_3x2in
  -o media=oe_3x3-label_3x3in
  -o media=na_index-3x5_3x5in
  -o media=oe_3.25x2-label_3.25x2in
  -o media=oe_3.25x5-label_3.25x5in
  -o media=oe_3.25x5.5-label_3.25x5.5in
  -o media=oe_3.25x5.83-label_3.25x5.83in
  -o media=oe_3.25x7.83-label_3.25x7.83in
  -o media=oe_3.5x1-label_3.5x1in
  -o media=oe_4x1-label_4x1in
  -o media=oe_4x2-label_4x2in
  -o media=oe_4x3-label_4x3in
  -o media=oe_4x4-label_4x4in
  -o media=oe_4x5-label_4x5in
  -o media=na_index-4x6_4x6in
  -o media=oe_4x6.5-label_4x6.5in
  -o media=oe_4x13-label_4x13in
  -o media=roll_max_4x39.6in
  -o media=roll_min_0.75x0.25in
  -o media-source=main-roll (default)
  -o media-top-offset=0in (default)
  -o media-top-offset=-15mm to 15mm
  -o media-tracking=mark (default)
  -o media-tracking=continuous
  -o media-tracking=web
  -o media-type=labels (default)
  -o media-type=continuous
  -o media-type=labels-continuous
  -o orientation-requested=none (default)
  -o orientation-requested=portrait
  -o orientation-requested=landscape
  -o orientation-requested=reverse-landscape
  -o orientation-requested=reverse-portrait
  -o print-color-mode=monochrome (default)
  -o print-color-mode=bi-level
  -o print-content-optimize=auto (default)
  -o print-content-optimize=graphic
  -o print-content-optimize=photo
  -o print-content-optimize=text-and-graphic
  -o print-content-optimize=text
  -o print-darkness=-100 to 100
  -o print-quality=normal (default)
  -o print-quality=draft
  -o print-quality=high
  -o print-speed=1in to 12in
  -o printer-resolution=203dpi
  -t 'TITLE'

Printer options:
  -o label-tear-offset=-15mm to 15mm
  -o printer-darkness=0 to 100
  -o printer-geo-location='geo:LATITUDE,LONGITUDE'
  -o printer-location='LOCATION'
  -o printer-organization='ORGANIZATION'
  -o printer-organizational-unit='UNIT/SECTION'
```

Ok... so I try to use `lprint modify ...` to change some of the paper feeding options. The change does not seem to have any effect.

Ok... so I try to append the options manually each time I print something, by adding them directly to the `lprint submit` command. Like this:

```sh
$ lprint -o printer-resolution=203dpi -o media-tracking=continuous -o media-type=labels-continuous -o media=na_index-4x6_4x6in -o orientation-requested=portrait pdf-label_portrait.png
lprint: Unable to print 'pdf-label_portrait.png' - Unsupported printer-resolution resolution value.
```

And it won't accept the option. Ok so does that mean 

1) it's not supported by the driver i selected?

2) Or does it mean that lprint has tried to communicate with my printer (using ZPL) and then via ZPL language the printer I have here will not let `lprint` to set that option to it?

3) Or is this supposed to be a global (not printer specific option), does it mean some other problem?

OK so resolution is not supported. When I remove that option I just get a different error for the other settings:

```sh
$ lprint submit -o media-tracking=continuous -o media-type=labels-continuous -o media=na_index-4x6_4x6in -o orientation-requested=portrait pdf-label_portrait.png
lprint: Unable to print 'pdf-label_portrait.png' - Unsupported media-col collection value.
$ lprint submit -o media-type=labels-continuous -o media=na_index-4x6_4x6in -o orientation-requested=portrait pdf-label_portrait.png
lprint: Unable to print 'pdf-label_portrait.png' - Unsupported media-col collection value.
$ lprint submit -o media=na_index-4x6_4x6in -o orientation-requested=portrait pdf-label_portrait.png
lprint: Unable to print 'pdf-label_portrait.png' - Unsupported media-col collection value.
```

It finaly accepts just the last portrait option in the list of options that were tried:

```sh
$ lprint submit -o orientation-requested=portrait pdf-label_portrait.png
xprinter-xp-460b-3
```

This then prints out the first 4 inches of this PNG test label image, who's specs are:

```sh
$ identify pdf-label_portrait.png 
pdf-label_portrait.png PNG 812x1218 926x1389+52+166 8-bit Gray 256c 55293B 0.000u 0:00.000
```

And the red light is flashing. At least the feed mechanism seems to have stopped at approximately the correct tear off point. I tear the label off and press the feed button once, that is currently flashing red. The printer then feeds out about 1.5 labels worh approx (these are 4x6 labels in a roll). And makes a positive chirp noise through it's internal speaker. The red light around the button is still flashing.

So that's usually the point where I power cycle the printer and manually re-feed the labels back onto the roll. So they don't all get wasted.

I don't suppose you happen to have any ideas / suggestions?

Currently my other option currently is to perhaps abandon `lprint` for now and try instead this https://github.com/kylemacfarlane/zplgrf python project. Which claims to fix the dithering by being a CUPS filter. So you plug it into CUPS ppd file. And see. Unfortunately that other project I cannot try it out yet. As cannot find the executable comdline program which it claims to install! Which is a shame because that is really my only issue with using the TSC driver over in CUPS that the dithering is broken.

Still hoping we can get `lprint` working at some point too. As this is also a very important piece of software going forwards.

**Comment by dreamcat4** [comment]
A small update:

Actually I was using a PNG image initially here because I didn't have any `.zpl` files to test with. And didn't know how to make a `.zpl file` (and I still don't know how to make them!).

However what I did find today in that other python module's source code was a folder of sample files including ZPL versions of some of the converted files. Which is to say that they are not very good test files but at least they are ZPL files. And with PNG equivalents. Here they are.

https://github.com/kylemacfarlane/zplgrf/tree/master/src/zplgrf/tests/input

I noticed that since trying to install this tool etc. And rebooting my printer. Then going back to `lprint` here and trying to print the ZPL instead of PNG that the feeding was working a little bit better. Still not 'correct' but at least this time when i press the paper feed mechanism now it correctly stops at the next tear off point. So that is great progress.

Then I tried printing one of those other PNG images. The result was that: the paper feeding sstill worked better now. Ok so it isn't PNG vs ZPL. So what about going back to my earlier test PNG from before? Does that feed better now? Why... yes it does!

So what else did I do here? Well I actually reinstalled the CUPS TSC printer driver. Which I had removed during my initial 'its not working right' tests with lprint here as per my comment #1 not feeding right etc.

So when I reinstalled the CUPS TSC driver I set properly again my paper size in there, the feeding type (continuus labels roll with gap) etc.

Now it still does not print the full 6 inches length: only the first 4 inches. Then it just plain old stops like midway. My naiive view (please dont assume this is true) is that maybe either this could be some bug, where the program does not finish printing the page. Or it could otherwise be that the thing thinks it's in landscape mode. Or that the media size is only 4x4 inches. I really have no idea which one of those things is true.

Anyhow this weird combination of CUPS + lprint is at least a small step forwards. The other thing I tried to do was install the other python module's cups filter by editing my CUPS ppd file from the TSC driver and adding the new filter line.

Unfortunately over in CUPS world it just keeps blinking and saying "processing". And does not print anything out. This I have seen before when I tried using the Zebra's CUPS drivers. It is stuck somehow. And there is nothing in the CUPS logs about it.

So that is where I am at right now... all a bit of a mess. And not sure much what is going on to be honest. So if you have any suggestions what I should be doing next then please let me know.

**Comment by dreamcat4** [comment]
And am now back to the feeding being about 1.5 labels worth. It's almost as if it's detecting the previous partial printout as the demarkation, when I try to wind back the roll. And none of these observations seems like a helpful type feedback in terms of figuring out what's really going on here. And the red light is flashing again. Have to power cycle it again.

**Comment by michaelrsweet** [comment]
This should fix the job option issues:

[master 08703cc] Lookup supported device-specific attribute values from the driver attributes.

**Comment by dreamcat4** [comment]
Thank you this has worked!
