### ISSUE TITLE
Documentation - Default lprint server port is 8000

### ISSUE THREAD

**Issue by brianbarr** [michaelrsweet/lprint#90]
Currently testing lprint v1.2 on a new debian 11 vm under VMware ESXi. 

Two issues thus far .. lprint sort of expects the avahi snap to be installed prior to installing lprint on linux via snap and complains if it isn't. 
So the docs should probably reflect that. 

Also the docs show this installation sequence:
sudo snap install core         (if you haven't already done so)
sudo snap install lprint
sudo snap connect lprint:raw-usb
sudo snap start lprint.lprint-server

The docs do not mention that the resulting lprint server web interface created has a default port of 8000 so the docs should probably be changed to reflect that as well. 

lsof -nP -iTCP -sTCP:LISTEN
COMMAND PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
lprint  628 root    6u  IPv4  13454      0t0  TCP *:8000 (LISTEN)
lprint  628 root    7u  IPv6  13455      0t0  TCP *:8000 (LISTEN)
sshd    711 root    3u  IPv4  13010      0t0  TCP *:22 (LISTEN)
sshd    711 root    4u  IPv6  13021      0t0  TCP *:22 (LISTEN)

**Comment by michaelrsweet** [comment]
Whether Avahi is provided as a snap or a system package is an implementation detail - not something I can easily document. Moreover, most of the desktop Linux distros install Avahi by default... (I know bare Debian is an exception to this)

**Comment by michaelrsweet** [comment]
Also, the default port is assigned dynamically, *starting* at 8000.

**Comment by michaelrsweet** [comment]
This is what the documentation says:

> - "-o server-port=NNN": Sets the network port number; the default is randomly assigned starting at 8000.
