### ISSUE TITLE
Lprint version 1.2 still prints "fuzzy" barcodes and text on LP2844 (Zebra EPL) label printer

### ISSUE THREAD

**Issue by brianbarr** [michaelrsweet/lprint#91]
The fuzzy print dithering issue is still present, even when setting "-o print-color-mode=bi-level" for the printer. 

The label with the "SAMPLE" overlay was generated by the Endicia app on a mac using a native epl driver on the same printer and it is crisp and legible vs the other label which was a barcode pdf and printed using lprint/airprint from a mac. 

So the printer is not the issue. 

Also there are a series of evenly spaced dots all over the label printed using lprint. 

See attached magnified pictures.. 

![IMG_8335](https://user-images.githubusercontent.com/4097816/210198352-7f1ed8d3-77c6-4816-a650-1e349c116112.jpeg)

![IMG_8336](https://user-images.githubusercontent.com/4097816/210198417-20e0141c-21b9-4fe1-a5b6-8d080553fb52.jpg)

**Comment by michaelrsweet** [comment]
Please attach the PPD file for the printer and a copy of the error_log file with debug logging enabled (`cupsctl --debug-logging`) showing a print job being sent to LPrint.

**Comment by brianbarr** [comment]
root@debian-lprint:~# snap refresh  lprint --channel=latest/edge
lprint (edge) 1.2.1 from Michael Sweet (michaelrsweet) refreshed
root@debian-lprint:~# reboot

I then printed two shipping labels and they came out blank.

**Comment by michaelrsweet** [comment]
Still working out some kinks in the ZPL driver...

**Comment by bnemura** [comment]
Most content that would be sent to a monochrome label printer is black&white, even if it's effectively grayscale in an image or PDF. Therefore dithering is usually undesirable - it's better to use a simple threshold algorithm to convert to monochrome.
The main tricky case is logos which aren't already monochrome or pre-dithered.

I see -o print-content-optimize listed in documentation. But I didn't see lprint/pappl/cups[v2] doing anything real with the value (did I miss it?). This would seem to be the appropriate option to select whether dithering is done (and default off for lprint IMHO).
If there were a smart dithering algorithm that could detect regions of graphic content that are intended to be multi-color and only dither those regions, that would be ideal.

Also, it may be helpful to note that Zebra "Link-OS" printers (e.g. ZD*s) can accept most PDF documents directly, with "apl.enable" set to "pdf".

**Comment by michaelrsweet** [comment]
@bnemura The "print-content-optimize" attribute doesn't get a lot of usage, mainly because modern clients generally are producing 'text-and-graphic' content when printing from office apps, and 'photo' content isn't normally targeted for these label printers because they aren't well-suited to that sort of content...  That said, the "print-color-mode" attribute is actually what you are looking for - 'monochrome' for shaded output and 'bi-level' for threshold.

What I've done for the next LPrint release (what is present in the master branch) is implement a specialized dithering and filtering algorithm that attempts to detect barcode content and threshold it while dithering everything else. This gets used for the "print-color-mode" 'auto' and 'monochrome' values, while 'bi-level' does thresholding exclusively.

WRT the PDF support in recent Zebra printers, that might be interesting to look at supporting but neither of my printers (GX420d and GX430t) seem to support it...

**Comment by michaelrsweet** [comment]
![IMG_6012](https://user-images.githubusercontent.com/488103/214317670-705df73e-bf51-4f73-bc4c-293ff33e6f26.jpg)

Shopify label printed to my 203dpi Zebra GX420d with the current LPrint master branch...

**Comment by bnemura** [comment]
@michaelrsweet well done, sir! Still some minor artifacts, but overall very impressive. The DataMatrix looks a little borderline, but still scans off my screen! I don't have a barcode grader handy.
Thanks for clarification on print-color-mode.
I'll see if we can get you a newer model Zebra for dev/test :)

**Comment by michaelrsweet** [comment]
So I'm going to close this out as "fixed" in 1.3 (next release real soon now). I do have a newer Zebra printer now and will investigate options for using the PDF support in a future release... Tracking that in issue #110.

**Comment by prohtex** [comment]
Hi @michaelrsweet As a longtime Zebra Mac user I'm excited to come across lprint. I have suffered with blurry dithered labels for a very long time. I'm a little confused though-is lprint a command-line tool only? How do I set up as a print driver on macos?

**Comment by prohtex** [comment]
> @prohtex
> 
> > Hi @michaelrsweet As a longtime Zebra Mac user I'm excited to come across lprint. I have suffered with blurry dithered labels for a very long time.
> > When I add a printer using the commands referenced in the documentation, I end up with a print queue that ether stops after each job, or goes into a print/stop loop, with hundreds of aborted jobs in the web interface queue. Any ideas?
> 
> If you enable debug logging (from the web interface), please file a new bug with the log and lprint.state files.

Hi Michael, what I realized is that I was using a model-specific driver that was not correct for my printer (I have a GK420D but was using GX420D). I've since switched to the generic drivers, and although I'm having the label feed issue documented in the other thread, they do print. Thanks!

**Comment by jonathan-sturges** [comment]
@michaelrsweet 
> What I've done for the next LPrint release (what is present in the master branch) is implement a specialized dithering and filtering algorithm that attempts to detect barcode content and threshold it while dithering everything else. This gets used for the "print-color-mode" 'auto' and 'monochrome' values, while 'bi-level' does thresholding exclusively.

Are there any additional settings in v1.3.1 that might help with barcode dithering?  I'm testing printing inventory labels using lprint v1.3.1 with a GK420t printer.  These labels have a Code 128 barcode that's getting dithered and don't scan.  I've tried "print-color-mode" auto and bi-level without difference.  I also set "print-content-optimize-mode=graphic" as well but it didn't seem to change anything.  Open to any suggestions and thanks for your work on lprint.

**Comment by michaelrsweet** [comment]
@jonathan-sturges 
> Are there any additional settings in v1.3.1 that might help with barcode dithering?

No, the algorithm is completely automatic. It would help to know what OS/Linux distro you are using and what version of CUPS since the rendering of the barcode might be the issue...

**Comment by jonathan-sturges** [comment]
That test was done on Armbian 26.2, with CUPS 2.4.7.

**Comment by profiteroles1** [comment]
We've developed a Mac app that's in pre-release testing that supports a wide variety of dither options and supports most Zebra printers. If anyone wants to try it out, let me know!
