### ISSUE TITLE
lPrint 1.2 Windows IPP Class Driver Printer and Media Settings

### ISSUE THREAD

**Issue by fspadini** [michaelrsweet/lprint#93]
When using Windows 11 Microsoft IPP Class Driver to connect to an lPrint server, little/no configuration for the printer or media are available.

Should the Windows 11 Microsoft IPP Class Driver expose any settings or options for the label printer configuration?

Setup:
lPrint Server lPrint 1.2.0 running on macOs
Printer Zebra ZD421 on Ethernet
Windows 11 Client: default printer discovery, Microsoft IPP Class Driver on IPP Port

Result:
![image](https://user-images.githubusercontent.com/445341/211653619-7ba3130b-7b54-4d15-8105-9cbaa33fe12c.png)
![image](https://user-images.githubusercontent.com/445341/211653717-a5aef3ac-1049-43e7-b18a-0832fdee6655.png)

**Comment by michaelrsweet** [comment]
You will have few options available via the Windows IPP class driver - basically just control over the label size and maybe color mode (grayscale and bi-level). The rest will all be defaulted.

If you want to see more, please provide feedback to Microsoft asking for support of more IPP attributes and values. Everything LPrint uses is registered with the Printer Working Group and thus is standard...
