### ISSUE TITLE
Regression - V1.2 can no longer print to mDNS-SD or Network Printer connected via USB/airport express device. 

### ISSUE THREAD

**Issue by brianbarr** [michaelrsweet/lprint#94]
I previously successfully connected my USB based Zebra LP-2844 using an apple airport express (via ethernet) to lprint v1.1 and sent a pdf label to it using MacOS 10.14.6 (with the "fuzzy label issue"). The printer is configured on the mac as an "airprint" printer. 

-- after switching to lprint 1.2 this does not work. 

Connecting the LP-2844 printer directly via USB to the debian 11 machine running the lprint v1.2 server software works (still with "fuzzy" labels). 

I tried adding the printer as a "Network Printer" using the IP address of the airport express and this also does not work with v1.2. 

Same result for a USB DYMO Turbo 450 plugged into the airport express. 

USB DYMO printer works perfectly printing a pdf label on the mac using vendor supplied DYMO CUPS driver via the airport express.

**Comment by michaelrsweet** [comment]
Hmm, nothing has changed WRT socket printing, so it should continue to work with your AirPort Express. What errors, if any, show up in the log file?

WRT the "fuzzy" labels, I've implemented a new dithering algorithm that is optimized for label printing for the next release of LPrint.

**Comment by brianbarr** [comment]
I installed lprint from the latest github source on a clean lbuntu 22.04.2 vm. 

The lprint service initially refused to start after enabling the service and a reboot. . after a bit of research it appears a "sudo ldconfig" is required after installation for lprint to work. I then tried adding a zebra LP8244 attached via USB to an airport express on the lan with ethernet.  Using the lprint server web interface, the printer was found on the lan and added successfully but I could not print a test page. The logs showed the printer could not be reached. I used "bonjour browser" to find the "PDL Data Stream" and IP address for the printer. I deleted the printer and I manually added  it back as a "network printer" in the lprint web interface and was then able to print a test label. Then after adding the zebra printer successfully on a mac as an airprint printer, I was able to print to it, but the result was a very poor quality "fuzzy label" still -- so it appears there is a bug in the code that finds the printer using mDNS-SD. I also tried adding a usb to airport express attached dymo 450 turbo using the same procedure .. this also did not work and another bug was shown in the logs .. bonjour browser showed the dymo was on port 9102 .. but the logs showed lprint was trying to talk the printer on port 9100. So there appears to be a bug in the mDNS-SD code. The fuzzy label issue remains.

**Comment by michaelrsweet** [comment]
The fuzzy label issues should be resolved by the latest code.

WRT the port number, are you trying to connect more than one printer to the Airport Express? That isn't officially supported by Apple, and the port number to printer mapping will be essentially random so I'm not sure what it would do in that case.

**Comment by michaelrsweet** [comment]
Closing due to no response; will re-open as needed...
