### ISSUE TITLE
Trying to Setup Zebra LP2844 Unable to Communicate

### ISSUE THREAD

**Issue by hagensieker** [michaelrsweet/lprint#96]
I have an LP 2884z configured as a network printer.  Installed LPrint 1.2 and went to the web @ localhost:8000

I can set up a printer and print a successful test page however when adding the printer via Bonjour (it shows up) it tells me it is unable to communicate with the printer at this time.  Using MacOS 16.2

Unable to connect to ‘Zebra LPrint ._ipps._tcp.local.’ due to an error. Would you still like to create the printer?

Any help appreciated.

**Comment by hagensieker** [comment]
Additional info from log files.

`I [2023-02-14T17:24:28.557Z] [Client 19] Closing connection from 'localhost'.
I [2023-02-14T17:26:32.577Z] [Client 23] Accepted connection from '192.168.20.201'.
I [2023-02-14T17:26:32.581Z] [Client 23] Starting HTTPS session.
E [2023-02-14T17:26:34.748Z] [Client 23] Unable to encrypt connection: Unable to create server credentials.
I [2023-02-14T17:26:34.748Z] [Client 23] Closing connection from '192.168.20.201'.`

**Comment by Siedlerchr** [comment]
i have the same problem with A Zebra ZT411, it seems like the error message is coming from PAPPL.
I tried both with and without "no-tls" option but that makes no difference
Running on macOS Ventura with latest release of LPrint
https://github.com/michaelrsweet/pappl/blob/7c37920ad4b2d244651e221debffe014c78cf5b3/pappl/client.c#L302-L316

**Comment by michaelrsweet** [comment]
Try creating the "/etc/cups/ssl" directory and see if that fixes things? I'll be building future packages with a newer version of libcups that automatically creates this directory as needed...

**Comment by Siedlerchr** [comment]
Yep, that solved the issue!
